POST http://localhost:5000/api/v1/register
Content-Type: application/json

{
   "username": "a",
   "password": "a",
   "confpassword": "a",
   "kelas": "6A"
}

###
POST http://localhost:5000/api/v1/login
Content-Type: application/json

{
   "username": "budiprayoga",
   "password": "budiprayoga"
}

### 
GET http://localhost:5000/api/v1/logout

### 
GET http://localhost:5000/api/v1/ekskul


###
POST http://localhost:5000/api/v1/ekskul
Content-Type: application/json

{
   "nama": "futsal",
   "deskripsi": "latihann sini dekk sama abg",
   "jadwal": "setiap senin dan kamis"
}

###
PATCH http://localhost:5000/api/v1/ekskul/4696f829-83e0-4fcc-bde8-3e652d15c687
Content-Type: application/json

{
   "nama": "futsal",
   "deskripsi": "latihann sini dekk sama abg",
   "jadwal": "setiap senin dan kamis"
}


###
GET http://localhost:5000/api/v1/ekskul

###
GET http://localhost:5000/api/v1/users

###
GET http://localhost:5000/api/v1/getMe


###
PATCH http://localhost:5000/api/v1/users/b594dea0-2623-44b3-9f30-be6af23570d9

# riwayat pendaftaran
###
GET http://localhost:5000/api/v1/riwayatPendaftaran

# Tampilkan Pendaftaran
###
GET http://localhost:5000/api/v1/pendaftaran

# Terima Pendaftaran
###
PATCH http://localhost:5000/api/v1/approve/553d19c0-4cf5-425d-9b5d-9125043c53c6

# Tolak Pendaftaran
###
PATCH http://localhost:5000/api/v1/disApprove/553d19c0-4cf5-425d-9b5d-9125043c53c6

###
GET http://localhost:5000/api/v1/pendaftaran/d3a58be8-2a60-485f-96f7-1f252caa941f

###
POST http://localhost:5000/api/v1/pendaftaran
Content-Type: application/json

{
   "deskripsi": "karena saya rasa saya mampu dan saya memiliki potensi",
   "id_ekskul": "d3a58be8-2a60-485f-96f7-1f252caa941f"
}